controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# home:
#     path: /homePage
#     controller: App\Controller\AuthController::loginAction